version: '3.1'
services:
  web:
    image: odoo:14.0
    container_name: odoo14_compose
    depends_on:
      - db_postgres
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./odoo_config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons

  db_postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo